blog/urls.py
from django.urls import path
from . import views
from . views import PostCreateView, PostUpdateView, PostDeleteView, download_combined_pdf

urlpatterns =[
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('Try/', views.Try, name='Try'),
    path('MainPage/', views.Try, name='MainPage'),
    path('detail/<int:post_id>/', views.post_detail, name='detail'),
    path('new_post/', PostCreateView.as_view(), name='new_post'),
    path('detail/<slug:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('detail/<slug:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('download_pdf/<int:post_id>/', download_combined_pdf, name='download_pdf'),
    #path('progress/', progress_view, name='progress_view'),
]

user/urls.py
from django.urls import path
from .import views 
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [ 
    path('register/', views.register, name='register'),
   # path('login/', LoginView.as_view(template_name='user/login.html') , name='login'),
    path('login/', views.login_user, name='login'),
   # path('logout/', LogoutView.as_view(template_name='user/logout.html') , name='logout'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('user.urls')),
] 

blog/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

#tables translelated into the db
# fields are title , content ...
# db is written using pythonand needed to be transformed to sql using commands 
#1. python manage.py makemigrations from python to sql
#2. python manage.py migrate execute the sqql and create the db

def user_directory_path(instance, filename):
    # File will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return os.path.join('user', f'{instance.author.id}', filename)
    
class Post( models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    post_date = models.DateTimeField(default=timezone.now) #created first time when post is created
    post_update = models.DateTimeField(auto_now=True) #updated every time the post is alterd
    author = models.ForeignKey(User, on_delete= models.CASCADE) #user is from django tables
    uploaded_report = models.FileField(upload_to=user_directory_path, blank=True, null=True)
    generated_pdf = models.FileField(upload_to='generated_pdfs/', blank=True, null=True)

    def __str__(self): #to return the title at the site administration
        return self.title
    
    def get_absolute_url (self):
         return reverse('detail', args=[self.pk])

    
    class Meta: #for the post to appear from new to old 
        ordering = ('-post_date',)

class Comment (models.Model): #inherits from models class
    name = models.CharField(max_length=30, verbose_name="الإسم")
    email = models.EmailField(verbose_name="البريد الإلكتروني")
    body = models.TextField(verbose_name="التعليق")
    comment_date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    def __str__(self):
        return 'علق {} على {}.'.format(self.name, self.post)
    class Meta:
        ordering = ('-comment_date',)




    

blog/forms.py
from django import forms
from .models import Comment, Post
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div
class NewComment(forms.ModelForm) :
    class Meta:
        model = Comment
        fields = ('name','email','body')
        
#add one mode field to take the compliance file from user
class PostCreateForm(forms.ModelForm) :
    title = forms.CharField(label='عنوان التقرير', max_length=50)
    content = forms.CharField(label=' وصف التقرير ', widget=forms.Textarea )
    uploaded_report = forms.FileField(label='ارفاق الملف', required=True)
   
    
    class Meta:
        model = Post
        fields = ['title','content','uploaded_report']


class PostUpdateForm(forms.ModelForm):
    title = forms.CharField(label='عنوان التقرير', max_length=50)
    content = forms.CharField(label=' وصف التقرير ', widget=forms.Textarea)
    
    class Meta:
        model = Post
        fields = ['title', 'content']

user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserCreationForm(forms.ModelForm):
    username = forms.CharField(label='اسم المستخدم', max_length=30, help_text='اسم المستخدم يجب ان لايحتوي على مسافات')
    email = forms.EmailField(label='البريد الإلكتروني')
    first_name = forms.CharField(label='الاسم الأول', max_length=30)
    last_name = forms.CharField(label='الاسم الثاني')
    password1 = forms.CharField(label='كلمة المرور' ,  widget=forms.PasswordInput(), min_length=8)
    password2 = forms.CharField(label='تأكيد كلمة المرور',  widget=forms.PasswordInput(), min_length=8)
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name',
                  'last_name','password1','password2' )
        
    def clean_password(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('كلمة المرور غير متطابقة')
        return cd['password2']
    
    def cleaned_username(self):
        cd = self.cleaned_data
        if User.objects.filter(username=cd['username']).exists():
            raise forms.ValidationError('يوجد مستخدم مسجل بهذا الاسم')
        return cd['username']
    

class LoginForm(forms.ModelForm):
    username = forms.CharField(label='اسم المستخدم', max_length=30)
    password = forms.CharField(label='كلمة المرور' ,  widget=forms.PasswordInput(), min_length=8)
    class Meta:
        model = User
        fields = ('username','password' )

class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(label='الاسم الأول', max_length=30)
    last_name = forms.CharField(label='الاسم الثاني')
    email = forms.EmailField(label='البريد الإلكتروني')

    class Meta :
        model = User
        fields = ('first_name','last_name','email')

class ProfileUpdateForm(forms.ModelForm):
   class Meta :
        model = Profile
        fields = ('image',)

blog/views.py
from typing import Optional
from django.shortcuts import render , get_object_or_404, redirect
from .models import Post, Comment

from django.core.files.base import ContentFile

from .forms import NewComment, PostCreateForm, PostUpdateForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django .contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from io import BytesIO

from django.http import HttpResponse
from .prepocessing import DataPreprocessor
import os
import pandas as pd
#from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
import pickle
import io


#creating views

def Try(request) :
    return render(request, 'blog/Try.html', context={'title':'Try'})

def MainPage(request) :
    return render(request, 'blog/TrMainPagey.html', context={'title':'MainPage'})

def home(request) :
    posts = Post.objects.all()
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context ={ 
    'title': 'الصفحة الرئيسية',
    'posts' : posts,
    'page' : page,
    }
    #blog/index.html refers to the file at the temblates folder 
    return render(request, 'blog/index.html', context)

def about(request) :
    return render(request, 'blog/about.html', context={'title':'من أنا'})

def post_detail (request, post_id):
    post=  get_object_or_404(Post,pk=post_id)
    comments = post.comments.filter(active=True) #show the comment if it is activated
    #التأكد من صحة البيانات قبل الحفظ
    if request.method == 'POST':
        comment_form = NewComment(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            comment_form = NewComment () #empty the form
    else:
        comment_form = NewComment()

    context={
    'title': post,
    'post': post,
    'comments' : comments,
    'comment_form': comment_form,
    }

    return render(request, 'blog/detail.html', context)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/new_post.html'
    form_class = PostCreateForm

    def form_valid(self, form):
        print(self.request.user)
        uploaded_report = self.request.FILES.get('uploaded_report', None)
        if uploaded_report:
            # Check if the file is an Excel file
            if uploaded_report.name.endswith('.xlsx') or uploaded_report.name.endswith('.xls'):
                if uploaded_report.size > 0:
                    fs = FileSystemStorage()
                    filename = fs.save(uploaded_report.name, uploaded_report)

                    # Get the full file path
                    file_path = os.path.join(fs.location, filename)

                    # Initialize the preprocessor with the uploaded file
                    preprocessor = DataPreprocessor(file_path)

                    # Perform preprocessing
                    preprocessed_data = preprocessor.preprocess()

                    # Store file path in session
                    self.request.session['uploaded_file_path'] = file_path
                    
                    # Generate PDF
                    pdf_data = DataPreprocessor.mergepdf(preprocessed_data)  # Assuming a function generate_pdf is defined

                    # Create a variable for the ContentFile
                    #pdf_content = pdf_data.getvalue()  # Get the content of the PDF file

                    # Create a ContentFile from the PDF data
                    pdf_content = ContentFile(pdf_data.getvalue(), name='generated_pdf.pdf')  # New Line


                    # Save the generated PDF to the Post model
                    # form.instance.generated_pdf.save('generated_pdf.pdf', ContentFile(pdf_content))

                    # Set the author and process the form
                    form.instance.author = self.request.user
                    form.instance.preprocessed_data = preprocessed_data # Assuming the Post model has a field for this

                    # Save the generated PDF to the Post model
                    form.instance.generated_pdf.save(pdf_content.name, pdf_content)  # New Line

                    return super().form_valid(form)
                else:
                    # File is empty, display warning message
                    messages.warning(self.request, 'الملف المرفق فارغ!')
                    return super().form_invalid(form)
            else:
                # File is not an Excel file, display warning message
                messages.warning(self.request, 'يرجى إرفاق ملف Excel فقط!')
                return super().form_invalid(form)
        else:
            # File not uploaded, display warning message
            messages.warning(self.request, 'يرجى إرفاق تقرير الالتزام قبل التأكيد!')
            return super().form_invalid(form)
        

def download_combined_pdf(request, post_id):
    # Retrieve the Post instance by ID
    post = get_object_or_404(Post, id=post_id)
    
    # Get the PDF file associated with the Post instance
    if post.generated_pdf:
        # Get the PDF file content
        pdf_file = post.generated_pdf

        response = HttpResponse(pdf_file.read(), content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{pdf_file.name}"'
        return response
    
    else:
        messages.error(request, 'No PDF file found for this post.')
        return redirect('upload')  # Redirect to a relevant page

class PostUpdateView(UserPassesTestMixin,LoginRequiredMixin,UpdateView):
    model = Post 
    template_name = 'blog/post_update.html'
    form_class = PostUpdateForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
       post = self.get_object()
       if self.request.user == post.author:
           return True
       else:
           return False
       
class PostDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    


""" file_path=''
def process_upload(request):
    if request.method == 'POST' and request.FILES['xlsx_file']:
        xlsx_file = request.FILES['xlsx_file']
        fs = FileSystemStorage()
        filename = fs.save(xlsx_file.name, xlsx_file)

        uploaded_file_url = fs.url(filename)
        
        # Load the XLSX file into a DataFrame
        file_path = os.path.join(fs.location, filename)
        #file_path1 = os.path.join(fs.location, filename)

        # Initialize the preprocessor with the uploaded file
        preprocessor = DataPreprocessor(file_path)

        # Perform preprocessing
        list = preprocessor.preprocess()

        return render(request, 'blog/user.html')
    return redirect('upload')
 """

""" @login_required
def download_combined_pdf(request):

    preprocessor1 = DataPreprocessor(file_path)
    pdf=preprocessor1.mergepdf() 
    
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=combined.pdf'
    #response['Content-Length'] = len(pdf_data)
    response.write(pdf.getvalue())
    print("hello")
    return response """

user/views.py
from django.shortcuts import render , redirect
from .forms import UserCreationForm, LoginForm, UserUpdateForm, ProfileUpdateForm
from django .contrib import messages
from django .contrib.auth import authenticate, login, logout
from blog.models import Post
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user= form.save(commit=False)
            new_user.set_password(form.cleaned_data['password1'])
            new_user.save()
            #username = form.cleaned_data['username']
            messages.success(
                request, f'تهانينا {new_user} لقد تمت عملية التسجيل بنجاح.')
            return redirect('login')
    else: 
       form = UserCreationForm()
    return render(request, 'user/register.html', {
        'title': 'التسجيل',
        'form': form,
    })

def login_user(request):
    form = LoginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('profile')
        else:
            messages.warning(
                request, 'هناك خطأ في اسم المستخدم أو كلمة المرور.')

    return render(request, 'user/login.html', {
        'title': 'تسجيل الدخول',
        'form': form,
    })

def logout_user(request):
    logout(request)
    return render(request, 'blog/index.html', {
        'title': 'تسجيل الخروج',
    })

@login_required(login_url='login')
def profile(request):
    posts = Post.objects.filter(author=request.user)
    posts_list = Post.objects.filter(author=request.user)
    paginator = Paginator(posts_list, 5)
    page = request.GET.get('page')
    try:
        posts_list = paginator.page(page)
    except PageNotAnInteger:
        posts_list = paginator.page(1)
    except EmptyPage:
        posts_list = paginator.page(paginator.num_pages)

    return render(request, 'user/profile.html', {
        'title': 'الملف الشخصي',
        'posts': posts,
        'page': page,
        'posts_list' : posts_list
    })

@login_required(login_url='login')
def profile_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid and profile_form.is_valid:
            user_form.save()
            profile_form.save()
            messages.success(
                request, 'تم تحديث الملف الشخصي.')
            return redirect('profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'title': 'تعديل الملف الشخصي',
        'user_form': user_form,
        'profile_form': profile_form,
    }

    return render(request, 'user/profile_update.html', context)

blog/templates/blog/Try.html
{% extends 'blog/base.html' %}
{% block content %}
{% load static %}
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel" style="display: flex; justify-content: center; align-items: center;">

    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1" style="background-color: gray;"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2" style="background-color: gray;"></button>
    </div>

    <div class="carousel-inner" style="text-align: center; margin-bottom: 20px;">
        <div class="carousel-item active">
            <div class="carousel-image-container">
                <img src="{% static 'blog/images/AiGA.png' %}" class="d-block" alt="..." style="width: auto; height: 80%; max-height: 200px;">
            </div>
            <div class="d-none d-md-block" style="color: gray;">
                <h5 style="color:#3B5286;">شريك داعـم</h5>
                <p>جمعية أهلية غير ربحية تهتم بتعزيز قدرات الذكاء الاصطناعي عبر تقديم التوعية والتدريب والاستشارات في مجال حوكمة الذكاء الاصطناعي والالتزام بأخلاقياته.</p>
            </div>
        </div>
        <div class="carousel-item">

            <div class="carousel-image-container">
                <img src="{% static 'blog/images/Sd.png' %}" class="d-block" alt="..." style="width: auto; height: 80%; max-height: 200px;">
            </div>
            <div class="d-none d-md-block" style="color: gray;">
                <h5 style="color:#3B5286;">شريك تقني</h5>
                <p>إحدى أبرز مقدمي خدمات الحوسبة السحابية الخاصة في المملكة العربية السعودية، حيث تتيح خبرتها تقديم حلول مبتكرة تُسهِّل الامتثال للأمن واللوائح التنظيمية.</p>
            </div>
        </div>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="fas fa-chevron-left" aria-hidden="true" style="color: gray;"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="fas fa-chevron-right" aria-hidden="true" style="color: gray;"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<style>
    .carousel-image-container {
        width: 100%; /* Make the container full width */
        height: 200px; /* Set a smaller fixed height for the container */
        overflow: hidden; /* Hide overflow to maintain shape */
        display: flex;
        justify-content: center;
        align-items: center; /* Center the image vertically */
    }

    .carousel-image-container img {
        width: auto; /* Maintain image aspect ratio */
        height: 100%; /* Make the image fill the container height */
        max-width: none; /* Prevent the image from exceeding its container */
    }

    .sponsorContainer {
        display: flex;
        flex-direction: column;
        gap: 10px;
    }

    .sponsorCard {
        border: none;
        transition: all 300ms cubic-bezier(0.19, 1, 0.22, 1);
        overflow: hidden;
        border-radius: 8px;
        box-shadow: 0 0 5px 0 rgba(0, 0, 0, 0.1);
        display: flex;
        justify-content: center;
        align-items: center;
        margin-bottom: 0;
    }

    .rectangular-sponsorCard img,
    .square-sponsorCard img {
        width: 100%;
        height: auto;
    }

    .rectangular-sponsorCard,
    .square-sponsorCard {
        height: 100px;
    }

    .sponsorcol-md-9 {
        width: 60%;
    }

    .sponsorcol-md-3 {
        width: 40%;
    }
</style>

{% endblock content %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="section wrapper d-flex justify-content-center align-items-center" data-aos="fade-up">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-6 col-lg-4 mb-4">
        <div class="card text-dark card-has-bg click-col">
          <div class="card-img-overlay d-flex flex-column align-items-center"> 
            <div class="card-body text-center">
              <img class="img-fluid rounded-circle border m-2" style="width:120px; height:120px;" src="{{ post.author.profile.image.url }}" alt="صورة الناشر">
              <div class="">
                <span class="text-secondary"> تم إنشـاء التقرير في :{{ post.post_date | date:'d-m-Y' }} </span>
                <h3 style="margin-top: 20%;">{{ post.title }}</h3>
                <p>{{ post.content }}</p>
                <a href="{% url 'download_pdf' post.id %}" class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded"> تحميل التقرير </a>
              </div>
            </div>
            <div class="card-footer">
              <div class="form-group btn-editing text-center">
                {% if post.author == user %}
                <a href="{% url 'post-update' post.id %}" class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded btn-secondary">تحرير</a>
                <a href="{% url 'post-delete' post.id %}" class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded btn-danger">حـذف</a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
.wrapper {
  margin: 10vh;
}

.card {
  border: none;
  transition: all 500ms cubic-bezier(0.19, 1, 0.22, 1);
  overflow: hidden;
  border-radius: 20px;
  min-height: 500px;
  box-shadow: 0 0 12px 0 rgba(0, 0, 0, 0.2);
}

.btn-rounded.btn-md {
  padding: 12px 35px;
  font-size: 16px;
}

.btn-primary,
.btn-primary.disabled {
  background: #02395D;
  border: 1px solid #02395D;
  -webkit-box-shadow: 0 2px 2px 0 rgba(116, 96, 238, 0.14), 0 3px 1px -2px rgba(116, 96, 238, 0.2), 0 1px 5px 0 rgba(116, 96, 238, 0.12);
  box-shadow: 0 2px 2px 0 rgba(116, 96, 238, 0.14), 0 3px 1px -2px rgba(116, 96, 238, 0.2), 0 1px 5px 0 rgba(116, 96, 238, 0.12);
  -webkit-transition: 0.2s ease-in;
  -o-transition: 0.2s ease-in;
  transition: 0.2s ease-in;
}

.btn-rounded {
  border-radius: 60px;
  padding: 7px 18px;
}

.btn:disabled {
  background-color: #BDBDBD;
  cursor: not-allowed;
}
</style>
{% endblock content %}

blog/templates/blog/latest_posts.html
<ul class="list-group-flush latest-post">
    {% for post in l_posts %}
    <li class="list-group-item latest-post-item">
        <a class="text-dark" href="{% url 'detail' post.id %}" style="text-decoration: none;">{{post.title}}</a>
    </li>
    {% empty %}
    <li class="list-group-item latest-post-item">لا يوجد تقارير</li>
    {% endfor %}
</ul>

blog/templates/blog/new_post.html
{% extends 'blog/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<section class="wrapper d-flex justify-content-center align-items-center"  data-aos="fade-up">
    <div class="container justify-content-center">
      <div class="row justify-content-center">
        <div class="col-sm-12 col-md-6 col-lg-4 mb-4 justify-content-center">
          {% if messages %}
          <div class="alert alert-warning" role="alert">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
          </div>
          {% endif %}
          <div class="card text-dark card-has-bg click-col justify-content-center" >
            <img class="card-img d-none" src="#" alt="#">
              <div class="card-img-overlay d-flex flex-column justify-content-center">
               <div class="card-body">
                <legend class="border-bottom pb-1 mb-3">إنشـاء تقريـر التزام جديـد</legend>

                    <form method="POST" enctype="multipart/form-data" id="uploadForm" >
                        {% csrf_token %}
                        {{form|crispy}}      
                </div>
                <input type="file" name="uploaded_report" id="id_uploaded_report" style="display: none" >
                
                        <div class="card-footer">
                        <div class="media text-center">
                            <!-- a button to confirm the changes -->
                            <input class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded" type="submit" value="تأكيد">  
                        </div>
                        </div>
              </div>
            </div>
            
                    </form>
          </div>

          <div class="col-md-4" style="margin-right: 10%;">
            <h3 style="color:#CBE54E ; margin-top: 40%; ">  NCA's ECC</h3>
            <h1 style="color:#3B5286;"> قياس الالتزام</h1>
            <h3 style="color:#3B5286 ;">  الضوابط الأساسية للأمن السيبراني </h3>
            
          </div>
      </div>
    </div>
  </section>

<style>

    .wrapper {
      margin: 10vh;
      display: flex;
      justify-content: center;
      align-items: center;

    }
  
    .card {
      border: none;
      transition: all 500ms cubic-bezier(0.19, 1, 0.22, 1);
      overflow: hidden;
      border-radius: 20px;
      min-height: 570px;
      box-shadow: 0 0 12px 0 rgba(0, 0, 0, 0.2);
    }
  

    .btn-rounded.btn-md {
        padding: 12px 35px;
        font-size: 16px;
    }
  
    .btn-primary,
    .btn-primary.disabled {
        background: #3B5286;
        border: 1px solid #3B5286;
        -webkit-box-shadow: 0 2px 2px 0 rgba(116, 96, 238, 0.14), 0 3px 1px -2px rgba(116, 96, 238, 0.2), 0 1px 5px 0 rgba(116, 96, 238, 0.12);
        box-shadow: 0 2px 2px 0 rgba(116, 96, 238, 0.14), 0 3px 1px -2px rgba(116, 96, 238, 0.2), 0 1px 5px 0 rgba(116, 96, 238, 0.12);
        -webkit-transition: 0.2s ease-in;
        -o-transition: 0.2s ease-in;
        transition: 0.2s ease-in;
    }
  
    .btn-rounded {
        border-radius: 60px;
        padding: 7px 18px;
    }
  
    .btn:disabled {
      background-color: #BDBDBD;
      cursor: not-allowed;
    }

  </style>


{% endblock content %}

blog/templates/blog/pagination.html
<div class=" pt-3 mt-4 mb-4 text-center">
    {% if page.has_next %}
    <a class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded" href="?page={{page.next_page_number}}"> التالي </a>
    {% else %}
    <a class="btn btn-outline-secondary mt-2 btn-rounded disabled" href="#">التالي</a>
    {% endif %}
    <span class="pr-4 pl-4"> صفحة {{page.number}} من {{page.paginator.num_pages}} </span>
    {% if page.has_previous %}
    <a class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded" href="?page={{page.previous_page_number}}"> السابق </a>
    {% else %}
    <a class="btn btn-outline-secondary mt-2 btn-rounded disabled" href="#">السابق</a>
    {% endif %}
</div>

<style>
.btn-rounded.btn-md {
    padding: 12px 35px;
    font-size: 16px;
}

.btn-primary,
  .btn-primary.disabled {
      background: #02395D;;
      border: 1px solid #02395D;;
      -webkit-box-shadow: 0 2px 2px 0 rgba(116, 96, 238, 0.14), 0 3px 1px -2px rgba(116, 96, 238, 0.2), 0 1px 5px 0 rgba(116, 96, 238, 0.12);
      box-shadow: 0 2px 2px 0 rgba(116, 96, 238, 0.14), 0 3px 1px -2px rgba(116, 96, 238, 0.2), 0 1px 5px 0 rgba(116, 96, 238, 0.12);
      -webkit-transition: 0.2s ease-in;
      -o-transition: 0.2s ease-in;
      transition: 0.2s ease-in;
  }

  .btn-rounded {
    border-radius: 60px;
    padding: 7px 18px;
}
</style>